public enum Profissao {
    MEDICO,
    MEDICA,
    PROFESSOR,
    PROFESSORA,
    JARDINEIRO,
    JARDINEIRA,
    PEDREIRO,
    PEDREIRA,
    MOTORISTA,
    DESENVOLVEDOR,
    DESENVOLVEDORA,
    ENGENHEIRO,
    ENGENHEIRA,
    ARQUITETO,
    ARQUITETA,
    OUTRAS;
}
